### ISSUE TITLE
训练时报错：AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Wangyy-moya** [tslgithub/image_class#23]
训练时，报下面的错误，请问怎么解决？
  
Traceback (most recent call last):
  File "train.py", line 174, in <module>
    main()
  File "train.py", line 170, in main
    train.start_train()
  File "train.py", line 148, in start_train
    X_train, X_test, y_train, y_test=self.load_data()
  File "train.py", line 55, in load_data
    _, w, h = img.shape[::-1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Wangyy-moya** [comment]
试了几个模型训练，都是报这个错，图像路径正确的，每次读取训练照片的进度条也不一样
![image](https://user-images.githubusercontent.com/41275719/90094957-e57d9400-dd61-11ea-87a4-d3d0f1c45305.png)
最高一次到96%就断掉

**Comment by Wangyy-moya** [comment]
我解决了

我出错的原因是数据集中有的照片没有进行转码，只是更改了后缀，所以在模型加载的时候会报错，用PIL工具将所有的jpg图片转换成为jpg图片就可以了（png格式的照片也是这样操作）。

**Comment by itismeJH** [comment]
嗯嗯，好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tslgithub/image_class"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月13日(星期四) 下午2:14
收件人:&nbsp;"tslgithub/image_class"<image_class@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [tslgithub/image_class] 训练时报错：AttributeError: 'NoneType' object has no attribute 'shape' (#23)





 
我解决了
 
我出错的原因是数据集中有的照片没有进行转码，只是更改了后缀，所以在模型加载的时候会报错，用PIL工具将所有的jpg图片转换成为jpg图片就可以了（png格式的照片也是这样操作）。
